services:
  mysql8:
    image: mysql:8.0.29
    restart: always
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "13316:3306"
    volumes:
      - ./script/mysql/:/docker-entrypoint-initdb.d/