apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-webook
spec:
  #副本数量
  replicas: 3
  selector:
    matchLabels:
      app: k8s-webook
  # template 是 Pod 的模版
  template:
    metadata:
      labels:
        app: k8s-webook
  # Pod具体信息
    spec:
      containers:
      - name: k8s-webook
        image: spigcoder/webook:v0.0.1
        ports:
        - containerPort: 8080