apiVersion: v1
kind: Service
metadata:
  name: webook-mysql
spec:
  ports:
    # 这个端口是我们进行访问的
    - port: 13309
      protocol: TCP
      targetPort: 3306
      nodePort: 30009
  selector:
    app: webook-mysql
  type: NodePort